language: dart
os: osx
install:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor
script:
  # - cd chessbotsmobile
  - ls
  - ./flutter/bin/flutter test
cache:
  directories:
    - $HOME/.pub-cache