name: chessbotsmobile
description: Create and battle chess bots!
version: 0.5.2+26
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
dependencies:
  flutter_crashlytics: ^0.2.1+1
  url_launcher: ^5.0.1
  shared_preferences: ^0.5.1+1
  flare_flutter: ^1.3.2
  firebase_core: ^0.3.1+1
  firebase_analytics: ^2.0.3
  cloud_firestore: ^0.9.5+2
  firebase_auth: ^0.8.1+4
  google_sign_in: ^4.0.1+1
  font_awesome_flutter: ^8.4.0
  chess: ">=0.6.5 <1.0.0"
  scoped_model: ">=1.0.0 <2.0.0"
  chess_vectors_flutter: ">=1.0.6 <2.0.0"
  rxdart: ^0.20.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
dev_dependencies:
  test:
  flutter_launcher_icons: ^0.7.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path_android: "images/icon-ios.png"
  image_path_ios: "images/icon-ios.png"
flutter:
  uses-material-design: true
  assets:
    - animations/chessbot.flr
    - images/icon.png
    - images/chess_board.png
    - images/brown_board.png
    - images/2.0x/brown_board.png
    - images/3.0x/brown_board.png
    - images/orange_board.png
    - images/2.0x/orange_board.png
    - images/3.0x/orange_board.png
    - images/green_board.png
    - images/2.0x/green_board.png
    - images/3.0x/green_board.png
    - images/dark_brown_board.png
    - images/2.0x/dark_brown_board.png
    - images/3.0x/dark_brown_board.png
  fonts:
    - family:  MyCustomIcons
      fonts:
      - asset: fonts/MyCustomIcons.ttf
    - family: Graduate
      fonts:
      - asset: fonts/Graduate-Regular.ttf
