import 'package:chessbotsmobile/models/gambit.dart';
import 'package:chessbotsmobile/shared/gambits.dart';

/// A list of all the gambit singletons
final List<Gambit> allGambits = [
  // offense
  CaptureUndefendedPiece(),
  CaptureQueen(),
  CaptureRook(),
  CaptureBishop(),
  CaptureBishopUsingPawn(),
  CaptureKnightUsingPawn(),
  CapturePawnUsingPawn(),
  CaptureQueenUsingPawn(),
  CaptureRookUsingPawn(),
  CaptureRandomUsingPawn(),
  CaptureRandomUsingBishop(),
  CaptureBishopUsingBishop(),
  CaptureBishopUsingBishopSafely(),
  CaptureKnightUsingBishop(),
  CapturePawnUsingBishop(),
  CaptureRookUsingBishop(),
  CaptureQueenUsingBishop(),
  CaptureRandomUsingKnight(),
  CaptureBishopUsingKnight(),
  CaptureKnightUsingKnight(),
  CapturePawnUsingKnight(),
  CaptureRookUsingKnight(),
  CaptureQueenUsingKnight(),
  CaptureQueenUsingQueen(),
  CaptureRookUsingQueen(),
  CaptureBishopUsingQueen(),
  CaptureKnightUsingQueen(),
  CapturePawnUsingQueen(),
  CaptureRandomUsingQueen(),
  CaptureBishopUsingKing(),
  CaptureKnightUsingKing(),
  CapturePawnUsingKing(),
  CaptureRookUsingKing(),
  CaptureQueenUsingKing(),
  CaptureRandomUsingKing(),
  CaptureRandomUsingRook(),
  CapturePawnUsingRook(),
  CaptureRookUsingRook(),
  CaptureQueenUsingRook(),
  CaptureKnightUsingRook(),
  CaptureBishopUsingRook(),
  CaptureKnight(),
  CapturePawn(),
  CaptureRandomPiece(),
  CheckOpponentUsingRandom(),
  CheckOpponentUsingPawn(),
  // CheckOpponentUsingKnight(),
  // CheckOpponentUsingBishop(),
  // CheckOpponentUsingRook(),
  // CheckOpponentUsingQueen(),
  // CheckOpponentUsingRandomSafely(),
  // CheckOpponentUsingPawnSafely(),
  // CheckOpponentUsingKnightSafely(),
  // CheckOpponentUsingBishopSafely(),
  // CheckOpponentUsingRookSafely(),
  // CheckOpponentUsingQueenSafely(),

  // defense
  CastleKingSide(),
  CastleQueenSide(),

  // promotions
  PromotePawnToQueen(),
  PromotePawnToRook(),
  PromotePawnToBishop(),
  PromotePawnToKnight(),
  PromotePawnToRandom(),
  PromoteWithCapture(),

  // movement
  MovePieceSafely(),
  MovePawn(),
  MoveKnight(),
  MoveBishop(),
  MoveRook(),
  MoveQueen(),
  MoveKing(),
  MoveQueenSafely(),
  MoveRookSafely(),
  MovePawnSafely(),
  MoveKnightSafely(),
  MoveBishopSafely(),
  // PawnToE4(),
  DevelopKnight(),
  DevelopBishop(),
  DevelopQueen(),
  DevelopRook(),
  DevelopPawn(),
];

/// Given a gambit's title, this map returns an instance corresponding gambit's singleton
///
/// Can be used to stand up a bot that was serialized in the db
Map<String, Gambit> gambitMap = Map.fromIterable(
  allGambits,
  key: (gambit) => gambit.title,
  value: (gambit) => gambit,
)..addAll({
    CheckmateOpponent().title: CheckmateOpponent(),
    MoveRandomPiece().title: MoveRandomPiece(),
    EmptyGambit().title: EmptyGambit(),
  });
